# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae9fefb7d299b007dc5a7ceed5b314197e6d3b817237a9af911aeb476e8c2f4214a65a5120bce81aaa07dd9acac63ab0e295489bfd1dafa0e3dd299d394c08a

test:
  secret_key_base: af086ff3f79ba919b7e343d73a536911ddf9b0058054820085b8f8d64aa30cb7ab1269de7b85b881d28c10b7daf78e6b19090f26fd2db3160317ed3af017b955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
